"""Object-native 3D generation and fine-tuning built on Diffusers."""

from ._version import __version__
from .data import (
    ImageCondition,
    MultiViewCondition,
    Object3DCondition,
    Object3DDataset,
    Object3DExample,
    PackedMeshBatch,
    TextCondition,
    preprocess_image_condition,
    preprocess_training_image_condition,
    validate_image_condition_pixels,
)
from .objects import (
    CameraRig,
    CoordinateSystem,
    GaussianSplatAsset,
    JSONPrimitive,
    JSONValue,
    Latent3DOutput,
    MeshAsset,
    Metadata,
    MetadataValidationError,
    Object3D,
    Object3DKind,
    Object3DPipelineOutput,
    Object3DValidationError,
    OVoxelAsset,
    PBRMaterial,
    SparseVoxelAsset,
    TensorDeviceError,
    TensorDTypeError,
    TensorShapeError,
)

__all__ = [
    "CameraRig",
    "CoordinateSystem",
    "GaussianSplatAsset",
    "ImageCondition",
    "JSONPrimitive",
    "JSONValue",
    "Latent3DOutput",
    "MeshAsset",
    "Metadata",
    "MetadataValidationError",
    "MultiViewCondition",
    "OVoxelAsset",
    "Object3D",
    "Object3DCondition",
    "Object3DDataset",
    "Object3DExample",
    "Object3DKind",
    "Object3DPipelineOutput",
    "Object3DValidationError",
    "PackedMeshBatch",
    "PBRMaterial",
    "SparseVoxelAsset",
    "TextCondition",
    "TensorDTypeError",
    "TensorDeviceError",
    "TensorShapeError",
    "__version__",
    "preprocess_image_condition",
    "preprocess_training_image_condition",
    "validate_image_condition_pixels",
]
